version: "3.4"

services:
  django:
    build: .
    command: python mis/manage.py runserver localhost:8080
    environment:
      - SECRET_KEY=12345
      - DEBUG=True
    ports:
      - 8080:8080
    volumes:
      - .:/app
