# Generated by Django 4.2 on 2023-04-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='params',
            name='type',
            field=models.CharField(choices=[(2, 'int'), (1, 'str'), (3, 'data')], max_length=20),
        ),
        migrations.AlterField(
            model_name='query',
            name='description',
            field=models.CharField(help_text='Краткое описание', max_length=200),
        ),
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.CharField(help_text='Введите имя запроса', max_length=100),
        ),
        migrations.AlterField(
            model_name='query',
            name='query',
            field=models.TextField(help_text='Тело запроса'),
        ),
    ]
