# Generated by Django 4.2 on 2023-04-07 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_alter_params_type_alter_query_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='params',
            name='type',
            field=models.IntegerField(choices=[(1, 'Str'), (2, 'Int'), (3, 'Date')]),
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('default_name', models.CharField(max_length=100)),
                ('actual_name', models.CharField(blank=True, max_length=100)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.query')),
            ],
        ),
    ]
