# Generated by Django 4.2 on 2023-04-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_uploadings_paramsvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadings',
            name='status',
            field=models.IntegerField(choices=[(1, 'Loaded'), (2, 'In Process')], default=2),
        ),
    ]
