# Generated by Django 4.2 on 2023-04-12 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_uploadings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadings',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='uploadings',
            name='create_date',
            field=models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
    ]
