# Generated by Django 4.2 on 2023-04-12 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_uploadings_comment_uploadings_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadings',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
    ]
