# Generated by Django 4.2 on 2023-04-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0007_alter_uploadings_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('dont_use', models.BooleanField(default=True)),
                ('in_process', models.BooleanField(default=False)),
            ],
        ),
    ]
