# Generated by Django 4.2 on 2023-04-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0008_dbusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadings',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Loaded'), (2, 'In Process')], default=0),
        ),
    ]
