# Generated by Django 4.2 on 2023-04-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0009_alter_uploadings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadings',
            name='file_path',
            field=models.CharField(default=''),
        ),
    ]
