# Generated by Django 4.2 on 2023-05-27 04:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0010_alter_uploadings_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='type',
            field=models.IntegerField(choices=[(0, 'Uploading'), (1, 'Augmentation')], default=0, help_text='Тип запроса'),
        ),
        migrations.CreateModel(
            name='Augmentations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(default='')),
                ('status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Loaded'), (2, 'In Process')], default=0)),
                ('create_date', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('uploaded_file', models.FileField(upload_to='')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.query')),
            ],
        ),
    ]
