# Generated by Django 4.2 on 2023-05-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0010_alter_uploadings_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='type',
            field=models.IntegerField(choices=[(0, 'Uploading'), (1, 'Augmentation')], default=0, help_text='Тип запроса'),
        ),
    ]
