# Generated by Django 4.2 on 2023-05-30 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0013_rename_query_uploadingfields_augmentation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadings',
            name='uploaded_file',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='uploadingfields',
            name='augmentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.uploadings'),
        ),
        migrations.DeleteModel(
            name='Augmentations',
        ),
    ]
