# Generated by Django 4.2 on 2023-05-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0015_augmentations_alter_uploadingfields_augmentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadings',
            name='uploaded_file',
        ),
    ]
