# Generated by Django 4.2 on 2023-05-30 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0016_remove_uploadings_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadingfields',
            name='augmentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.uploadings'),
        ),
        migrations.DeleteModel(
            name='Augmentations',
        ),
    ]
