# Generated by Django 4.2 on 2023-05-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0017_alter_uploadingfields_augmentation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadings',
            name='uploaded_file',
            field=models.CharField(default=''),
        ),
    ]
